version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app

  backend:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn transaction.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app

  celery_worker:
    build: .
    restart: always
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    command: >
      celery -A transaction.tasks worker --loglevel=info
    networks:
      - app

volumes:
  postgres_data:

networks:
  app: